### PR TITLE
api was broken, removed type query in order to fix

### PR DESCRIPTION
**Pull request by Mateo-Wallace**
Old api query
`https://api.jikan.moe/v4/anime?q=${search}&sfw&limit=${jikanLimit}&type=anime&order_by=members&sort=desc`

New api query
`https://api.jikan.moe/v4/anime?q=${search}&sfw&limit=${jikanLimit}&order_by=members&sort=desc`

### CODE REVIEW

**Review by dcrowdev — APPROVED** [review]
its awesome this thing is still up!

**Comment by Bfunk54** [comment]
Such good times, thanks for fixing and noticing @Mateo-Wallace ! Everyone doing well?

**Comment by Mateo-Wallace** [comment]
Doing great! Living my dream. Working remote in Colombia right now. Just a TA for the bootcamp at the moment but I have a couple interviews lined up. How about you guys what are yall doing post bootcamp?

**Comment by Bfunk54** [comment]
> Doing great! Living my dream. Working remote in Colombia right now. Just a TA for the bootcamp at the moment but I have a couple interviews lined up. How about you guys what are yall doing post bootcamp?

Really good to hear brotha! I'm still working coding for the small company in Daytona Beach, but started back at school and am starting UCF's computer science bachelor's program this fall, so pretty excited for that. Doing school and working right now, it's been a lot but it's been good, and I'm excited.

**Comment by dcrowdev** [comment]
Awesome to hear from you guys! Glad you both are doing well! I've also just been working for the same company for about a year now here in Orlando. It's online e-commerce and I'm learning a ton! I'll never forget my first projects with you guys!

**Pull request merged**
